query GetTrackers($offset: Int = 0, $limit: Int = 20) {
  trackers(offset: $offset, limit: $limit) {
    totalCount
    items { id serialNumber alias }
  }
}
query TrackerBySN($serialNumber: String!) {
  trackerBySN(serialNumber: $serialNumber) { id serialNumber alias }
}
mutation AddTracker($input: AddTrackerInput!) {
  addTracker(input: $input) { success message }
}
mutation DeleteTracker($id: ID!) {
  deleteTracker(id: $id) { success message }
}
mutation UpdateTracker($id: ID!, $input: UpdateTrackerInput!) {
  updateTracker(id: $id, input: $input) { success message }
}
