query GetPOIs($offset: Int = 0, $limit: Int = 20) {
  pois(offset: $offset, limit: $limit) {
    totalCount
    items { id title color latitude longitude }
  }
}
mutation AddPOI($input: AddPOIInput!) {
  addPOI(input: $input) { success message }
}
mutation DeletePOI($id: ID!) {
  deletePOI(id: $id) { success message }
}
